name: Test Web

on:
  push

jobs:
  test:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: "Run E2E tests for the web application"
        working-directory: ./frontend/web
        run: |
          npm install
          npm run e2e:headless
