name: Test Mobile

on:
  push

jobs:
  test:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: "Run E2E tests for the mobile application"
        working-directory: ./frontend/mobile
        run: |
          yarn install
          yarn e2e:headless
