name: Tests Web

on:
  push

jobs:
  validate:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        working-directory: ./frontend/web
        uses: actions/setup-node@v3
        run:
          npm install
      - name: "Run e2e tests for the web application"
        working-directory: ./frontend/web
        uses: cypress-io/github-action@v6
        run:
          npm run build
          npm run start
          npm run cypress:run
