name: ESLint Web

on:
  push

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: "Run web application eslint"
        working-directory: ./frontend/web
        run: |
          npm install
          npm run eslint .
