name: Test Backend

on:
  push

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: "Run unit tests for the backend application"
        working-directory: ./backend
        run: |
          npm install
          npm run test
