name: Unit Tests Web

on:
  push

jobs:
  validate:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: "Run unit tests for the web application"
        working-directory: ./frontend/web
        run: |
          npm install
          npm run test
